### ISSUE TITLE
"Unable to parse environment files for application startup" on Mac

### ISSUE THREAD

**Issue by gbraad** [gbraad/html5-google-authenticator#49]
This is a Mac specific error which is reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1087362 It seems to occur since the update to Firefox 34.

**Comment by gbraad** [comment]
The Firefox marketplace does not handle uninstalls as these are performed based on the platform you are running; Android link can be removed/uninstalled from the launcher, Mac only needs a delete action (move to Trash), Windows wants you to go to your Add/Remove Software, etc...

**Comment by gbraad** [comment]
Thanks, as mentioned a simple removal of the application should do the trick as the keys are stored in a profile folder. Any further comments related to the "Unable to parse ..." issue should be directed to Mozilla's bug report.

**Comment by Unsinkable2** [comment]
Yup - remove and re-install did the trick.  It feels a bit like removing the engine when you only want to replace a flat tire, but it worked.

**Comment by gbraad** [comment]
@Unsinkable2 Thanks for confirming.

**Comment by pschulz** [comment]
I fixed it this way:

1. Removed "GAuth authenticator" from /Applications
2. Installed "GAuth" via the marketplace (consider the other name!)
3. mv $HOME/Library/Application\ Support/gauthauthenticator-78ef3156e1ca5b74c14beac161614be7 $HOME/Library/Application\ Support/gauth-78ef3156e1ca5b74c14beac161614be7
4. Start GAuth. Your keys are there.

**Comment by gbraad** [comment]
Thanks for the detailed description and yes, please notice the name change.
