### ISSUE TITLE
Export (backup) keys to file or remote storage

### ISSUE THREAD

**Issue by gbraad** [gbraad/html5-google-authenticator#52]
Implement means to backup keys or export to a remote storage, such as Dropbox.

**Comment by gbraad** [comment]
In Firefox 34/Developer edition the word 'export' is seen as a reserved keyword. Please replace it with any other string.

**Comment by multiwebinc** [comment]
I tried this out today with the current version and the output file contains only. Looks like you need to json encode it: `[object Object]`

**Comment by gbraad** [comment]
Fixed... but not functional for most mobile browsers.
Alternative would be to generate QR codes... but actually I do not think this function is a good idea.
