### ISSUE TITLE
Indentation style

### ISSUE THREAD

**Issue by multiwebinc** [gbraad/html5-google-authenticator#56]
All indentation should use 4 spaces for Javascript and 2 spaces for html and css. See:

http://javascript.crockford.com/code.html
https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml

**Comment by gbraad** [comment]
Javascript indentation style is enforced by JSHint and Scrutiziner https://scrutinizer-ci.com/g/gbraad/html5-google-authenticator/

Note: external libraries are not considered.

**Comment by multiwebinc** [comment]
If I understand correctly, according to https://github.com/jshint/jshint/issues/1809, indentation style is no longer enforced by JSHint.

**Comment by gbraad** [comment]
Doing:

```shell
$ npm test
```

would start linting the code. This is also enforced on Drone.io and Travis as part of the code analysis during the CI-process.

I do not care much for the JSHint and some of the opinions of Douglas Crockford when it comes to Javascript. Sure, a lot he is correct about such as semi-colon insertion, but indentation styles are personal (or project-based). It is enforced for what is sane... especially to prevent mixed cases (tabs+spaced)
